language: node_js
before_script:
- npm install -g gatsby-cli
node_js:
- '12'
install:
- npm ci
deploy:
  app: khu-stack
  provider: heroku
  api_key:
    secure: EYizxJTw393SWrc4nADfdydSzaga7IENluAeVp11NM3LnLKqlPdgyf48zX0YE10P522qcGWcP4poDH04LgvmeX9y4D2CoOEjy4knFPn5dLLD8ARFFvul+LqXm0zNyLRWWlFierKe9KNXeeUVErEcK4i4oSpfo88jUW79zImxWVpb8zZlUON+A1XBrYXrNdzfBiavubiF6fZh5+4r0XREfn82AzY2/GoLULd7gp1wGD1c6PCKpkqsvQN0nQhp4qDHk9KLEmAQXPXqy0qD1Iztve2UP7swuXXpESnlDQX/omRz0gSR1gJv+HBtQxVslKB7jiTDvlhJ54b8L+ARpm0eFDZBEVqQO66+36qh+ezie9Cv+Icq9OJxAcN7ddkGD2aUPE+pTA0LDjEv+tGngnGvoXNuJU9G6JynjYZLyj1AOroOu2Syhwl7leJflfKwXgEJo4YQlOh9w6wARenTo31/dvetCPRoBDiED7FiNoONFAVPE8Wxv0a27ZV3yGozeIivUhPC6OhkCsrbNTdJQXQOibap8x/rHzHKwUrMtonOTVeKc8a98YVzOfD4ji6Ooe5YYqQ9+UuorNme2wS9hl8z/dhEkCSuV2TgoS9o72vnUaqOJgkl5qrt0lzoBda8YvoeisbSsjzzfSxajH+4j6dQ8Az/V8TfrsNL+4F7IqJNRZo=
