language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "12"
install:
  - npm ci
deploy:
  provider: heroku:git
  api_key:
    secure: HEROKU_API_KEY
  git: https://git.heroku.com/khu-stack.git
  on: main
  edge: true
